default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk upgrade
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

stages:
  - build
  - test

build_alpine:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:latest .
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:latest

build_debian:
  stage: build
  script:
    - docker build -f Dockerfile.debian -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian .
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian

test:
  stage: test
  script:
    - apk add curl
    - docker run -e PORT=8080 -d $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine
    - docker run -e PORT=8081 -d $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian
    - sleep 20
    - curl -v http://127.0.0.1:8080/status
    - curl -v http://127.0.0.1:8081/status