default:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk update && apk upgrade
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin

stages:
  - build
  - test

build_alpine:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:alpine -t $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:latest .
    - docker push $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:alpine
    - docker push $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:latest

build_debian:
  stage: build
  script:
    - docker build -f Dockerfile.debian -t $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:debian .
    - docker push $CI_REGISTRY/gdt-bahnar/gocrapi/gocrapi:debian