image: docker:latest

before_script:
  - apk update && apk upgrade
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - test

build_alpine:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:latest .
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:latest

build_debian:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile.debian -t $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian .
    - docker push $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian

test:
  stage: test
  script:
    - apk add curl
    - docker run -e PORT=8080 -d $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:alpine
    - docker run -e PORT=8081 -d $CI_REGISTRY/gdt-bahnar/ocrviet/ocrviet:debian
    - sleep 20
    - curl -v http://127.0.0.1:8080/status
    - curl -v http://127.0.0.1:8081/status