FROM golang:buster

USER root
RUN mkdir /src

ADD . /src
WORKDIR /src
# Install tesseract and data
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y gcc g++ libtesseract-dev tesseract-ocr-vie
# Get best trainned data
RUN wget -O /usr/share/tesseract-ocr/4.00/tessdata/vie.traineddata https://github.com/tesseract-ocr/tessdata_best/blob/master/vie.traineddata?raw=true
# Build ocr server
RUN go get -u all && \
    go build -o ocrviet

ENV PORT "8080"
CMD ["/src/ocrviet"]
