name: Publish Docker image
on: workflow_dispatch
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to GitHub Container Registry
        run: |
          echo $GHCR_PAT | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker build . -t ghcr.io/${{ github.repository }}:latest         
          docker run -d ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          GIN_MODE: release
